# Numpy :
Numpy is one of the most useful and important Libarary in python. Numpy library is implemented using C++, and hence its functions and operations are quite faster than using Lists in Python with Loops and other methods.
* Usually Numpy contains various functions for Mathematical, Arithemetic, Statistics, Arrays and etc.
* Today I am going to deal with some of the questions from Numpy.
* And I am going to mention some of the most common NumPy functions. 

In [13]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [14]:
#checking the type of arr and accessing any element from index
print(arr[0])
print(arr[1])
type(arr)

1
2


numpy.ndarray

In [15]:
#dot product of two arrays
arr1 = np.array([3,4,5])
arr2 = np.array([5,6,7])
np.dot(arr1, arr2)

74

Operations with Multi-Dimensional Arrays


In [16]:
#Creation of Multidimensional array
arr_multiD_1 = np.array([[2,3,5], [4,5,6]])
arr_multiD_2 = np.array([[10,11,12], [13,14,15]])
print(arr_multiD_1)
print(arr_multiD_2)

[[2 3 5]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


In [17]:
#Checking the shape of any array and datatype
print(arr_multiD_2.dtype)
print(arr_multiD_2.shape)

int64
(2, 3)


In [18]:
#Performing the matrix multiplication
np.matmul(arr_multiD_1, arr1)
#OR
arr_multiD_1 @ arr1

array([43, 62])

In [19]:
#Conacatenating two arrays
np.concatenate((arr_multiD_1, arr_multiD_2),1)

array([[ 2,  3,  5, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

In [20]:
#Arithemetic operations on array
print(arr1*3)
print(arr+1)
print(arr/2)
print(arr-2)

[ 9 12 15]
[2 3 4]
[0.5 1.  1.5]
[-1  0  1]


In [22]:
#Comparision Operators between arrays
print(arr1 == arr2)
print(arr1!=arr2)
print(arr1>arr2)
print(arr1<arr2)

[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


In [23]:
#To check the no of equal values in both the arrays we use .sum()
(arr1 == arr2).sum()

0

In [24]:
#To access array elements using indexing
arr_multiD_1[0,2]

5

In [25]:
multiD = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10]])
multiD[1:, 1:3]

array([[5, 6],
       [8, 9]])

Other ways via which we can create arrays

In [30]:
#To create array of zeroes, ones, identitity
print(np.zeros((3,3)))
print(np.ones([2,3,2]))
print(np.eye(3)*5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [43]:
#To create array of random numbers in the range 1>arr>0
print(np.random.rand(2,3))
print()
#To create arrays of random numbers in the range -2<arr<2
print(np.random.randn(3,4))
print()
#To create an array of random integers
print(np.random.randint(10,30,size=(4,4)))
print()
#To create array using other functions
print(np.arange(10,90,step=3))
print()
print(np.full([2,3], fill_value=42))
print()
print(np.linspace(1,20,2))

[[0.40887406 0.46749613 0.71644754]
 [0.49944108 0.94667784 0.43331773]]

[[-0.44528787 -0.8464665   0.02633867 -0.9639914 ]
 [-0.90420913  0.54093034 -0.58273497 -0.51086105]
 [-0.83912512 -0.14168114  1.46269104  0.07593339]]

[[18 28 23 19]
 [22 18 27 27]
 [17 27 18 19]
 [22 18 28 24]]

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88]

[[42 42 42]
 [42 42 42]]

[ 1. 20.]


array([5, 4, 3])